/**
 * Mock Hub Expansion Data
 * Sample data for testing hub expansion features with real Melbourne coordinates
 */

import type { CustomRegion, RegionalHub, HubExpansionScenario } from '../types/hub';
import type { StoreLocation } from '../types/inventory';

// Mock stores with real Melbourne coordinates
export const mockStoresWithCoordinates: StoreLocation[] = [
  // CBD & Inner City
  {
    id: 'store-001',
    name: 'CBD Central Grocer',
    type: 'retail_store',
    code: 'STORE001',
    contact_person: 'John Smith',
    email: 'john@cbdgrocer.com',
    phone: '0412345678',
    address_line1: '250 Elizabeth Street',
    address_line2: null,
    city: 'Melbourne',
    state: 'VIC',
    postal_code: '3000',
    country: 'Australia',
    latitude: -37.8136,
    longitude: 144.9631,
    region: 'CBD & Inner City',
    restock_cycle_days: 7,
    minimum_stock_level: 40,
    maximum_stock_level: 80,
    ideal_stock_percentage: 80,
    average_daily_sales: 5.5,
    preferred_delivery_day: 'Monday',
    preferred_delivery_time: '9:00 AM',
    seasonal_multiplier: 1.0,
    seasonal_notes: null,
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  // Northern Corridor
  {
    id: 'store-002',
    name: 'Brunswick Asian Mart',
    type: 'retail_store',
    code: 'STORE002',
    contact_person: 'Sarah Lee',
    email: 'sarah@brunswickmart.com',
    phone: '0423456789',
    address_line1: '123 Sydney Road',
    address_line2: null,
    city: 'Brunswick',
    state: 'VIC',
    postal_code: '3056',
    country: 'Australia',
    latitude: -37.7691,
    longitude: 144.9584,
    region: 'Northern Corridor',
    restock_cycle_days: 7,
    minimum_stock_level: 35,
    maximum_stock_level: 70,
    ideal_stock_percentage: 80,
    average_daily_sales: 4.8,
    preferred_delivery_day: 'Tuesday',
    preferred_delivery_time: '10:00 AM',
    seasonal_multiplier: 1.0,
    seasonal_notes: null,
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  {
    id: 'store-003',
    name: 'Coburg Village Market',
    type: 'retail_store',
    code: 'STORE003',
    contact_person: 'Mike Chen',
    email: 'mike@coburgmarket.com',
    phone: '0434567890',
    address_line1: '45 Sydney Road',
    address_line2: null,
    city: 'Coburg',
    state: 'VIC',
    postal_code: '3058',
    country: 'Australia',
    latitude: -37.7333,
    longitude: 144.9633,
    region: 'Northern Corridor',
    restock_cycle_days: 7,
    minimum_stock_level: 30,
    maximum_stock_level: 60,
    ideal_stock_percentage: 80,
    average_daily_sales: 4.2,
    preferred_delivery_day: 'Tuesday',
    preferred_delivery_time: '11:00 AM',
    seasonal_multiplier: 1.0,
    seasonal_notes: null,
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  // Eastern Suburbs
  {
    id: 'store-004',
    name: 'Box Hill Asian Grocers',
    type: 'retail_store',
    code: 'STORE004',
    contact_person: 'Linda Wang',
    email: 'linda@boxhillgrocers.com',
    phone: '0445678901',
    address_line1: '1 Main Street',
    address_line2: 'Box Hill Central',
    city: 'Box Hill',
    state: 'VIC',
    postal_code: '3128',
    country: 'Australia',
    latitude: -37.8192,
    longitude: 145.1233,
    region: 'Eastern Suburbs',
    restock_cycle_days: 7,
    minimum_stock_level: 45,
    maximum_stock_level: 90,
    ideal_stock_percentage: 80,
    average_daily_sales: 6.2,
    preferred_delivery_day: 'Wednesday',
    preferred_delivery_time: '9:00 AM',
    seasonal_multiplier: 1.0,
    seasonal_notes: null,
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  // Bayside & South
  {
    id: 'store-005',
    name: 'St Kilda Fine Foods',
    type: 'retail_store',
    code: 'STORE005',
    contact_person: 'Emma Rodriguez',
    email: 'emma@stkildafoods.com',
    phone: '0456789012',
    address_line1: '78 Acland Street',
    address_line2: null,
    city: 'St Kilda',
    state: 'VIC',
    postal_code: '3182',
    country: 'Australia',
    latitude: -37.8677,
    longitude: 144.9778,
    region: 'Bayside & South',
    restock_cycle_days: 7,
    minimum_stock_level: 38,
    maximum_stock_level: 75,
    ideal_stock_percentage: 80,
    average_daily_sales: 5.0,
    preferred_delivery_day: 'Thursday',
    preferred_delivery_time: '10:00 AM',
    seasonal_multiplier: 1.2,
    seasonal_notes: 'Higher demand during summer (beach tourism)',
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  // Western Suburbs
  {
    id: 'store-006',
    name: 'Footscray Market Store',
    type: 'retail_store',
    code: 'STORE006',
    contact_person: 'Nguyen Tran',
    email: 'nguyen@footscraymarket.com',
    phone: '0467890123',
    address_line1: '55 Leeds Street',
    address_line2: 'Footscray Market',
    city: 'Footscray',
    state: 'VIC',
    postal_code: '3011',
    country: 'Australia',
    latitude: -37.8017,
    longitude: 144.8994,
    region: 'Western Suburbs',
    restock_cycle_days: 7,
    minimum_stock_level: 42,
    maximum_stock_level: 85,
    ideal_stock_percentage: 80,
    average_daily_sales: 5.8,
    preferred_delivery_day: 'Friday',
    preferred_delivery_time: '8:00 AM',
    seasonal_multiplier: 1.0,
    seasonal_notes: null,
    parent_location_id: null,
    assigned_user_id: null,
    sms_notifications_enabled: true,
    email_notifications_enabled: true,
    emergency_restock_enabled: true,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// Mock regional hubs
export const mockRegionalHubs: RegionalHub[] = [
  {
    id: 'hub-001',
    location_id: 'loc-hub-001',
    hub_type: 'shipping_company',
    partner_company_name: 'Melbourne Fast Logistics',
    coverage_regions: ['Northern Corridor', 'CBD & Inner City'],
    max_storage_capacity: 1000,
    current_stock_level: 650,
    ideal_buffer_stock: 200,
    stores_served: 3,
    average_delivery_time_hours: 2.5,
    total_monthly_shipments: 24,
    commission_rate: 5.0,
    monthly_storage_fee: 200,
    contract_duration_months: 12,
    contract_start_date: '2024-01-01',
    contract_end_date: '2025-01-01',
    total_commission_earned: 2400,
    total_storage_fees_paid: 1200,
    is_active: true,
    onboarding_date: '2024-01-01',
    operational_since: '2024-01-15',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-10-26T00:00:00Z',
    location: {
      id: 'loc-hub-001',
      name: 'Melbourne Fast Logistics Warehouse',
      code: 'HUB001',
      address_line1: '89 Industrial Drive',
      city: 'Brunswick',
      region: 'Northern Corridor',
      latitude: -37.7650,
      longitude: 144.9600,
    },
  },
  
  {
    id: 'hub-002',
    location_id: 'loc-hub-002',
    hub_type: 'restaurant',
    partner_company_name: 'Golden Wok Restaurant',
    coverage_regions: ['Eastern Suburbs'],
    max_storage_capacity: 500,
    current_stock_level: 280,
    ideal_buffer_stock: 100,
    stores_served: 1,
    average_delivery_time_hours: 3.0,
    total_monthly_shipments: 8,
    commission_rate: 7.0,
    monthly_storage_fee: 150,
    contract_duration_months: 12,
    contract_start_date: '2024-03-01',
    contract_end_date: '2025-03-01',
    total_commission_earned: 1680,
    total_storage_fees_paid: 900,
    is_active: true,
    onboarding_date: '2024-03-01',
    operational_since: '2024-03-15',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-10-26T00:00:00Z',
    location: {
      id: 'loc-hub-002',
      name: 'Golden Wok Restaurant',
      code: 'HUB002',
      address_line1: '234 Whitehorse Road',
      city: 'Box Hill',
      region: 'Eastern Suburbs',
      latitude: -37.8200,
      longitude: 145.1250,
    },
  },
];

// Mock hub expansion scenarios
export const mockHubScenarios: HubExpansionScenario[] = [
  {
    id: 'scenario-001',
    scenario_name: 'Western Suburbs Hub - Footscray Distribution Center',
    target_regions: ['Western Suburbs'],
    status: 'planning',
    proposed_hub_type: 'shipping_company',
    partner_company_name: 'West Melbourne Shipping Co',
    partner_contact_person: 'David Johnson',
    partner_phone: '0498765432',
    partner_email: 'david@westmelshipping.com',
    proposed_address: '123 Somerville Road, Footscray VIC 3011',
    proposed_latitude: -37.8050,
    proposed_longitude: 144.9020,
    proposed_storage_capacity: 800,
    proposed_buffer_stock: 150,
    stores_in_target_area: 9,
    current_monthly_shipments: 18,
    current_avg_delivery_cost: 15.00,
    current_total_monthly_cost: 270.00,
    projected_monthly_bulk_shipments: 4,
    projected_bulk_shipment_cost: 97.20,
    projected_local_delivery_cost: 90.00,
    projected_hub_commission: 450.00,
    projected_storage_fee: 200.00,
    projected_total_monthly_cost: 837.20,
    monthly_savings: -567.20, // Negative! Not viable
    break_even_months: null,
    roi_percentage: null,
    setup_cost: 5000.00,
    estimated_monthly_operating_cost: 837.20,
    proposed_commission_rate: 5.0,
    proposed_storage_fee: 200.00,
    contract_duration_months: 12,
    created_by: 'user-admin',
    created_at: '2024-10-20T00:00:00Z',
    approved_by: null,
    approved_at: null,
    rejection_reason: null,
    business_case: 'Explore hub opportunity in western suburbs to reduce delivery costs and improve response times.',
    risk_assessment: 'Low store density may not justify hub economics.',
    updated_at: '2024-10-20T00:00:00Z',
  },
  
  {
    id: 'scenario-002',
    scenario_name: 'Bayside Hub - Chapel Street Distribution',
    target_regions: ['Bayside & South', 'CBD & Inner City'],
    status: 'approved',
    proposed_hub_type: 'warehouse',
    partner_company_name: 'Bayside Warehouse Solutions',
    partner_contact_person: 'Rachel Green',
    partner_phone: '0487654321',
    partner_email: 'rachel@baysidewarehouse.com',
    proposed_address: '567 Chapel Street, South Yarra VIC 3141',
    proposed_latitude: -37.8400,
    proposed_longitude: 144.9900,
    proposed_storage_capacity: 1200,
    proposed_buffer_stock: 250,
    stores_in_target_area: 12,
    current_monthly_shipments: 24,
    current_avg_delivery_cost: 15.00,
    current_total_monthly_cost: 360.00,
    projected_monthly_bulk_shipments: 4,
    projected_bulk_shipment_cost: 129.60,
    projected_local_delivery_cost: 120.00,
    projected_hub_commission: 600.00,
    projected_storage_fee: 200.00,
    projected_total_monthly_cost: 1049.60,
    monthly_savings: -689.60, // Also not viable
    break_even_months: null,
    roi_percentage: null,
    setup_cost: 8000.00,
    estimated_monthly_operating_cost: 1049.60,
    proposed_commission_rate: 5.0,
    proposed_storage_fee: 200.00,
    contract_duration_months: 12,
    created_by: 'user-admin',
    created_at: '2024-10-15T00:00:00Z',
    approved_by: 'user-ceo',
    approved_at: '2024-10-18T00:00:00Z',
    rejection_reason: null,
    business_case: 'High-value area with tourism traffic. Hub can serve both CBD and bayside stores efficiently.',
    risk_assessment: 'Higher setup costs but strong long-term potential.',
    updated_at: '2024-10-18T00:00:00Z',
  },
];

// Mock custom regions (same as default but as data)
export const mockCustomRegions: CustomRegion[] = [
  {
    id: 'region-001',
    name: 'CBD & Inner City',
    description: 'Melbourne CBD and immediate inner suburbs',
    type: 'default',
    color: '#DC2626',
    boundary_type: 'postcode_list',
    postcodes: ['3000', '3002', '3004', '3006', '3008', '3010', '3065', '3066', '3067', '3121'],
    boundary_polygon: null,
    center_latitude: -37.8136,
    center_longitude: 144.9631,
    radius_km: null,
    hub_priority: 'HIGH',
    estimated_stores: 1,
    suggested_hub_location: 'Queen Victoria Market area',
    rationale: 'Highest density retail area',
    transport_access: 'All major roads converge here',
    is_active: true,
    created_by: 'system',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  {
    id: 'region-002',
    name: 'Northern Corridor',
    description: 'Inner and outer northern suburbs',
    type: 'default',
    color: '#2563EB',
    boundary_type: 'postcode_list',
    postcodes: ['3051', '3053', '3054', '3055', '3056', '3057', '3058', '3072', '3073'],
    boundary_polygon: null,
    center_latitude: -37.7650,
    center_longitude: 144.9600,
    radius_km: null,
    hub_priority: 'HIGH',
    estimated_stores: 2,
    suggested_hub_location: 'Brunswick - Sydney Road',
    rationale: 'Strong multicultural food scene',
    transport_access: 'Hume Highway, Sydney Road',
    is_active: true,
    created_by: 'system',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  
  {
    id: 'region-003',
    name: 'Eastern Suburbs',
    description: 'Box Hill and eastern corridor',
    type: 'default',
    color: '#16A34A',
    boundary_type: 'postcode_list',
    postcodes: ['3101', '3102', '3103', '3104', '3105', '3122', '3123', '3124', '3125', '3126', '3128'],
    boundary_polygon: null,
    center_latitude: -37.8192,
    center_longitude: 145.1233,
    radius_km: null,
    hub_priority: 'MEDIUM',
    estimated_stores: 1,
    suggested_hub_location: 'Box Hill Central',
    rationale: 'Large Asian community',
    transport_access: 'Eastern Freeway',
    is_active: true,
    created_by: 'system',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];
