/**
 * Mock Product Data
 * Demonstrates multi-product line support
 */
import type { Product, ProductCategoryInfo } from '../types/product';

export const mockProducts: Product[] = [
  // Chili Oil Products
  {
    id: '1',
    sku: 'CHILI-MILD-500',
    name: 'Mild Chili Oil 500ml',
    description: 'Perfect for beginners, gentle heat with rich flavor',
    category: 'Chili Oil',
    spiceLevel: 'mild',
    volume_ml: 500,
    packagingType: 'Glass Bottle',
    basePrice: 25.00,
    wholesalePrice: 20.00,
    currency: 'AUD',
    minimumStockLevel: 50,
    reorderQuantity: 100,
    isActive: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '2',
    sku: 'CHILI-HOT-500',
    name: 'Hot Chili Oil 500ml',
    description: 'For those who love serious heat',
    category: 'Chili Oil',
    spiceLevel: 'hot',
    volume_ml: 500,
    packagingType: 'Glass Bottle',
    basePrice: 30.00,
    wholesalePrice: 25.00,
    currency: 'AUD',
    minimumStockLevel: 50,
    reorderQuantity: 100,
    isActive: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '3',
    sku: 'CHILI-EXTRA-250',
    name: 'Extra Hot Chili Oil 250ml',
    description: 'Extreme heat for true chili lovers',
    category: 'Chili Oil',
    spiceLevel: 'extra_hot',
    volume_ml: 250,
    packagingType: 'Glass Bottle',
    basePrice: 20.00,
    wholesalePrice: 16.00,
    currency: 'AUD',
    minimumStockLevel: 30,
    reorderQuantity: 50,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },

  // Sauce Products
  {
    id: '4',
    sku: 'SAUCE-SOY-1L',
    name: 'Premium Soy Sauce 1L',
    description: 'Traditional brewed soy sauce',
    category: 'Sauce',
    spiceLevel: 'none',
    volume_ml: 1000,
    packagingType: 'Plastic Bottle',
    basePrice: 18.00,
    wholesalePrice: 14.00,
    currency: 'AUD',
    minimumStockLevel: 40,
    reorderQuantity: 80,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '5',
    sku: 'SAUCE-OYSTER-500',
    name: 'Oyster Sauce 500ml',
    description: 'Rich and savory oyster sauce',
    category: 'Sauce',
    spiceLevel: 'none',
    volume_ml: 500,
    packagingType: 'Glass Bottle',
    basePrice: 22.00,
    wholesalePrice: 18.00,
    currency: 'AUD',
    minimumStockLevel: 35,
    reorderQuantity: 70,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },

  // Condiment Products
  {
    id: '6',
    sku: 'COND-GARLIC-250',
    name: 'Crispy Garlic Condiment 250g',
    description: 'Crunchy fried garlic topping',
    category: 'Condiment',
    weight_g: 250,
    packagingType: 'Jar',
    basePrice: 15.00,
    wholesalePrice: 12.00,
    currency: 'AUD',
    minimumStockLevel: 25,
    reorderQuantity: 50,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '7',
    sku: 'COND-SESAME-200',
    name: 'Sesame Paste 200g',
    description: 'Pure ground sesame paste',
    category: 'Condiment',
    weight_g: 200,
    packagingType: 'Jar',
    basePrice: 12.00,
    wholesalePrice: 9.50,
    currency: 'AUD',
    minimumStockLevel: 20,
    reorderQuantity: 40,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },

  // Seasoning Products
  {
    id: '8',
    sku: 'SEASON-SZECHUAN-100',
    name: 'Szechuan Pepper Mix 100g',
    description: 'Aromatic Szechuan peppercorn blend',
    category: 'Seasoning',
    spiceLevel: 'medium',
    weight_g: 100,
    packagingType: 'Pouch',
    basePrice: 14.00,
    wholesalePrice: 11.00,
    currency: 'AUD',
    minimumStockLevel: 30,
    reorderQuantity: 60,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
  {
    id: '9',
    sku: 'SEASON-FIVE-SPICE-150',
    name: 'Five Spice Powder 150g',
    description: 'Traditional Chinese five spice',
    category: 'Seasoning',
    weight_g: 150,
    packagingType: 'Pouch',
    basePrice: 16.00,
    wholesalePrice: 13.00,
    currency: 'AUD',
    minimumStockLevel: 25,
    reorderQuantity: 50,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },

  // Oil Products
  {
    id: '10',
    sku: 'OIL-SESAME-500',
    name: 'Toasted Sesame Oil 500ml',
    description: 'Fragrant toasted sesame oil',
    category: 'Oil',
    volume_ml: 500,
    packagingType: 'Glass Bottle',
    basePrice: 24.00,
    wholesalePrice: 19.00,
    currency: 'AUD',
    minimumStockLevel: 30,
    reorderQuantity: 60,
    isActive: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2025-10-20T00:00:00Z',
  },
];

export const mockProductCategories: ProductCategoryInfo[] = [
  {
    id: '1',
    name: 'Chili Oil',
    description: 'Various spice levels of chili oil',
    icon: '🌶️',
    color: '#DC2626',
    productCount: 3,
  },
  {
    id: '2',
    name: 'Sauce',
    description: 'Traditional Asian sauces',
    icon: '🥫',
    color: '#7C2D12',
    productCount: 2,
  },
  {
    id: '3',
    name: 'Condiment',
    description: 'Toppings and garnishes',
    icon: '🧄',
    color: '#65A30D',
    productCount: 2,
  },
  {
    id: '4',
    name: 'Seasoning',
    description: 'Spice blends and seasonings',
    icon: '✨',
    color: '#9333EA',
    productCount: 2,
  },
  {
    id: '5',
    name: 'Oil',
    description: 'Cooking and finishing oils',
    icon: '🫗',
    color: '#CA8A04',
    productCount: 1,
  },
];
