/**
 * Mock Data for Development - Melbourne Region
 * Used to visualize dashboard before backend is ready
 * Updated with Melbourne/Victoria distributors and geolocation data
 */
import type {
  DashboardStats,
  LowStockAlert,
  DistributorOverview,
  RecentActivity,
  QuickAction,
} from '../types/dashboard';

export const mockDashboardStats: DashboardStats = {
  totalInventory: 25450,
  activeDistributors: 10,
  totalDistributors: 10,
  lowStockAlerts: 8,
  pendingTransfers: 3,
};

export const mockLowStockAlerts: LowStockAlert[] = [
  {
    id: '1',
    productName: 'Hot Chili Oil 500ml',
    sku: 'CHILI-HOT-500ML',
    locationName: 'North Melbourne Distributor',
    locationCode: 'DIST001',
    currentStock: 15,
    minimumStock: 50,
    severity: 'critical',
  },
  {
    id: '2',
    productName: 'Mild Chili Oil 500ml',
    sku: 'CHILI-MILD-500ML',
    locationName: 'South Yarra Distributor',
    locationCode: 'DIST002',
    currentStock: 20,
    minimumStock: 50,
    severity: 'critical',
  },
  {
    id: '3',
    productName: 'Medium Chili Oil 500ml',
    sku: 'CHILI-MED-500ML',
    locationName: 'Box Hill Distributor',
    locationCode: 'DIST004',
    currentStock: 35,
    minimumStock: 50,
    severity: 'warning',
  },
  {
    id: '4',
    productName: 'Extra Hot Chili Oil 250ml',
    sku: 'CHILI-EXTRA-250ML',
    locationName: 'Geelong Distributor',
    locationCode: 'DIST005',
    currentStock: 40,
    minimumStock: 50,
    severity: 'warning',
  },
];

/**
 * Melbourne Region Distributors
 * Covering major suburbs and regions around Melbourne
 * With real geolocation coordinates for map view
 */
export const mockDistributors: DistributorOverview[] = [
  {
    id: '1',
    name: 'North Melbourne Distributor',
    code: 'DIST001',
    city: 'North Melbourne',
    state: 'Victoria',
    region: 'North',
    status: 'critical',
    totalStock: 180,
    lowStockItems: 3,
    lastRestocked: '2025-10-20',
    phone: '+61 3 9329 1111',
    latitude: -37.7995,
    longitude: 144.9491,
    address: '123 Arden St, North Melbourne',
    postcode: '3051',
  },
  {
    id: '2',
    name: 'South Yarra Distributor',
    code: 'DIST002',
    city: 'South Yarra',
    state: 'Victoria',
    region: 'South',
    status: 'low_stock',
    totalStock: 450,
    lowStockItems: 2,
    lastRestocked: '2025-10-22',
    phone: '+61 3 9866 2222',
    latitude: -37.8397,
    longitude: 145.0001,
    address: '456 Toorak Rd, South Yarra',
    postcode: '3141',
  },
  {
    id: '3',
    name: 'CBD Central Distributor',
    code: 'DIST003',
    city: 'Melbourne CBD',
    state: 'Victoria',
    region: 'CBD',
    status: 'healthy',
    totalStock: 3200,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+61 3 9654 3333',
    latitude: -37.8136,
    longitude: 144.9631,
    address: '789 Collins St, Melbourne',
    postcode: '3000',
  },
  {
    id: '4',
    name: 'Box Hill Distributor',
    code: 'DIST004',
    city: 'Box Hill',
    state: 'Victoria',
    region: 'East',
    status: 'low_stock',
    totalStock: 520,
    lowStockItems: 1,
    lastRestocked: '2025-10-21',
    phone: '+61 3 9890 4444',
    latitude: -37.8197,
    longitude: 145.1233,
    address: '321 Station St, Box Hill',
    postcode: '3128',
  },
  {
    id: '5',
    name: 'Geelong Distributor',
    code: 'DIST005',
    city: 'Geelong',
    state: 'Victoria',
    region: 'West',
    status: 'healthy',
    totalStock: 2100,
    lowStockItems: 0,
    lastRestocked: '2025-10-23',
    phone: '+61 3 5221 5555',
    latitude: -38.1499,
    longitude: 144.3617,
    address: '555 Moorabool St, Geelong',
    postcode: '3220',
  },
  {
    id: '6',
    name: 'Footscray Distributor',
    code: 'DIST006',
    city: 'Footscray',
    state: 'Victoria',
    region: 'West',
    status: 'healthy',
    totalStock: 1850,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+61 3 9687 6666',
    latitude: -37.7985,
    longitude: 144.9007,
    address: '888 Barkly St, Footscray',
    postcode: '3011',
  },
  {
    id: '7',
    name: 'Glen Waverley Distributor',
    code: 'DIST007',
    city: 'Glen Waverley',
    state: 'Victoria',
    region: 'East',
    status: 'healthy',
    totalStock: 4200,
    lowStockItems: 0,
    lastRestocked: '2025-10-25',
    phone: '+61 3 9560 7777',
    latitude: -37.8780,
    longitude: 145.1629,
    address: '999 Springvale Rd, Glen Waverley',
    postcode: '3150',
  },
  {
    id: '8',
    name: 'Brunswick Distributor',
    code: 'DIST008',
    city: 'Brunswick',
    state: 'Victoria',
    region: 'North',
    status: 'healthy',
    totalStock: 1600,
    lowStockItems: 0,
    lastRestocked: '2025-10-23',
    phone: '+61 3 9380 8888',
    latitude: -37.7645,
    longitude: 144.9602,
    address: '147 Sydney Rd, Brunswick',
    postcode: '3056',
  },
  {
    id: '9',
    name: 'St Kilda Distributor',
    code: 'DIST009',
    city: 'St Kilda',
    state: 'Victoria',
    region: 'South',
    status: 'low_stock',
    totalStock: 380,
    lowStockItems: 2,
    lastRestocked: '2025-10-19',
    phone: '+61 3 9534 9999',
    latitude: -37.8677,
    longitude: 144.9807,
    address: '258 Acland St, St Kilda',
    postcode: '3182',
  },
  {
    id: '10',
    name: 'Dandenong Distributor',
    code: 'DIST010',
    city: 'Dandenong',
    state: 'Victoria',
    region: 'South East',
    status: 'healthy',
    totalStock: 2450,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+61 3 9791 0000',
    latitude: -37.9871,
    longitude: 145.2154,
    address: '369 Lonsdale St, Dandenong',
    postcode: '3175',
  },
];

export const mockRecentActivity: RecentActivity[] = [
  {
    id: '1',
    type: 'transfer',
    description: 'Transferred 200 units of CHILI-MILD-500ML to North Melbourne',
    timestamp: '2025-10-25T10:30:00Z',
    user: 'Tien Tran',
  },
  {
    id: '2',
    type: 'sms',
    description: 'Sent low stock alerts to 5 distributors',
    timestamp: '2025-10-25T09:15:00Z',
    user: 'Tien Tran',
  },
  {
    id: '3',
    type: 'product',
    description: 'Added new product: CHILI-GARLIC-500ML',
    timestamp: '2025-10-25T08:45:00Z',
    user: 'Tien Tran',
  },
  {
    id: '4',
    type: 'transfer',
    description: 'Transferred 150 units of CHILI-HOT-500ML to Glen Waverley',
    timestamp: '2025-10-24T16:20:00Z',
    user: 'Tien Tran',
  },
  {
    id: '5',
    type: 'adjustment',
    description: 'Inventory adjustment: +50 units at Main Warehouse',
    timestamp: '2025-10-24T14:10:00Z',
    user: 'Tien Tran',
  },
];

export const mockQuickActions: QuickAction[] = [
  {
    id: '1',
    label: 'Transfer Stock',
    icon: '🚚',
    href: '/transfers/new',
    color: 'red',
  },
  {
    id: '2',
    label: 'Add Product',
    icon: '📦',
    href: '/products/new',
    color: 'blue',
  },
  {
    id: '3',
    label: 'Send SMS',
    icon: '📱',
    href: '/sms/send',
    color: 'green',
  },
  {
    id: '4',
    label: 'View Reports',
    icon: '📊',
    href: '/reports',
    color: 'yellow',
  },
  {
    id: '5',
    label: 'Manage Distributors',
    icon: '👥',
    href: '/distributors',
    color: 'gray',
  },
];

/**
 * Melbourne Region Boundaries
 * For map view filtering and regional analysis
 */
export const melbourneRegions = {
  CBD: {
    name: 'Melbourne CBD',
    center: { lat: -37.8136, lng: 144.9631 },
    zoom: 15,
  },
  North: {
    name: 'Northern Suburbs',
    center: { lat: -37.7645, lng: 144.9602 },
    zoom: 12,
  },
  South: {
    name: 'Southern Suburbs',
    center: { lat: -37.8677, lng: 144.9807 },
    zoom: 12,
  },
  East: {
    name: 'Eastern Suburbs',
    center: { lat: -37.8780, lng: 145.1629 },
    zoom: 12,
  },
  West: {
    name: 'Western Suburbs',
    center: { lat: -37.7985, lng: 144.9007 },
    zoom: 12,
  },
  'South East': {
    name: 'South Eastern Suburbs',
    center: { lat: -37.9871, lng: 145.2154 },
    zoom: 12,
  },
};
