/**
 * Mock Data for Development
 * Used to visualize dashboard before backend is ready
 */
import type {
  DashboardStats,
  LowStockAlert,
  DistributorOverview,
  RecentActivity,
  QuickAction,
} from '../types/dashboard';

export const mockDashboardStats: DashboardStats = {
  totalInventory: 25450,
  activeDistributors: 10,
  totalDistributors: 10,
  lowStockAlerts: 8,
  pendingTransfers: 3,
};

export const mockLowStockAlerts: LowStockAlert[] = [
  {
    id: '1',
    productName: 'Hot Chili Oil 500ml',
    sku: 'CHILI-HOT-500ML',
    locationName: 'North Region Distributor',
    locationCode: 'DIST001',
    currentStock: 15,
    minimumStock: 50,
    severity: 'critical',
  },
  {
    id: '2',
    productName: 'Mild Chili Oil 500ml',
    sku: 'CHILI-MILD-500ML',
    locationName: 'South Region Distributor',
    locationCode: 'DIST002',
    currentStock: 20,
    minimumStock: 50,
    severity: 'critical',
  },
  {
    id: '3',
    productName: 'Medium Chili Oil 500ml',
    sku: 'CHILI-MED-500ML',
    locationName: 'East Coast Distributor',
    locationCode: 'DIST004',
    currentStock: 35,
    minimumStock: 50,
    severity: 'warning',
  },
  {
    id: '4',
    productName: 'Extra Hot Chili Oil 250ml',
    sku: 'CHILI-EXTRA-250ML',
    locationName: 'Sabah Distributor',
    locationCode: 'DIST005',
    currentStock: 40,
    minimumStock: 50,
    severity: 'warning',
  },
];

export const mockDistributors: DistributorOverview[] = [
  {
    id: '1',
    name: 'North Region Distributor',
    code: 'DIST001',
    city: 'Penang',
    state: 'Penang',
    status: 'critical',
    totalStock: 180,
    lowStockItems: 3,
    lastRestocked: '2025-10-20',
    phone: '+60121111111',
  },
  {
    id: '2',
    name: 'South Region Distributor',
    code: 'DIST002',
    city: 'Johor Bahru',
    state: 'Johor',
    status: 'low_stock',
    totalStock: 450,
    lowStockItems: 2,
    lastRestocked: '2025-10-22',
    phone: '+60122222222',
  },
  {
    id: '3',
    name: 'Central Region Distributor',
    code: 'DIST003',
    city: 'Seremban',
    state: 'Negeri Sembilan',
    status: 'healthy',
    totalStock: 3200,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+60123333333',
  },
  {
    id: '4',
    name: 'East Coast Distributor',
    code: 'DIST004',
    city: 'Kuantan',
    state: 'Pahang',
    status: 'low_stock',
    totalStock: 520,
    lowStockItems: 1,
    lastRestocked: '2025-10-21',
    phone: '+60124444444',
  },
  {
    id: '5',
    name: 'Sabah Distributor',
    code: 'DIST005',
    city: 'Kota Kinabalu',
    state: 'Sabah',
    status: 'healthy',
    totalStock: 2100,
    lowStockItems: 0,
    lastRestocked: '2025-10-23',
    phone: '+60125555555',
  },
  {
    id: '6',
    name: 'Sarawak Distributor',
    code: 'DIST006',
    city: 'Kuching',
    state: 'Sarawak',
    status: 'healthy',
    totalStock: 1850,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+60126666666',
  },
  {
    id: '7',
    name: 'Klang Valley Distributor',
    code: 'DIST007',
    city: 'Petaling Jaya',
    state: 'Selangor',
    status: 'healthy',
    totalStock: 4200,
    lowStockItems: 0,
    lastRestocked: '2025-10-25',
    phone: '+60127777777',
  },
  {
    id: '8',
    name: 'Melaka Distributor',
    code: 'DIST008',
    city: 'Melaka',
    state: 'Melaka',
    status: 'healthy',
    totalStock: 1600,
    lowStockItems: 0,
    lastRestocked: '2025-10-23',
    phone: '+60128888888',
  },
  {
    id: '9',
    name: 'Kedah Distributor',
    code: 'DIST009',
    city: 'Alor Setar',
    state: 'Kedah',
    status: 'low_stock',
    totalStock: 380,
    lowStockItems: 2,
    lastRestocked: '2025-10-19',
    phone: '+60129999999',
  },
  {
    id: '10',
    name: 'Perak Distributor',
    code: 'DIST010',
    city: 'Ipoh',
    state: 'Perak',
    status: 'healthy',
    totalStock: 2450,
    lowStockItems: 0,
    lastRestocked: '2025-10-24',
    phone: '+60120000000',
  },
];

export const mockRecentActivity: RecentActivity[] = [
  {
    id: '1',
    type: 'transfer',
    description: 'Transferred 200 units of CHILI-MILD-500ML to DIST001',
    timestamp: '2025-10-25T10:30:00Z',
    user: 'Tien Tran',
  },
  {
    id: '2',
    type: 'sms',
    description: 'Sent low stock alerts to 5 distributors',
    timestamp: '2025-10-25T09:15:00Z',
    user: 'Tien Tran',
  },
  {
    id: '3',
    type: 'product',
    description: 'Added new product: CHILI-GARLIC-500ML',
    timestamp: '2025-10-25T08:45:00Z',
    user: 'Tien Tran',
  },
  {
    id: '4',
    type: 'transfer',
    description: 'Transferred 150 units of CHILI-HOT-500ML to DIST007',
    timestamp: '2025-10-24T16:20:00Z',
    user: 'Tien Tran',
  },
  {
    id: '5',
    type: 'adjustment',
    description: 'Inventory adjustment: +50 units at Main Warehouse',
    timestamp: '2025-10-24T14:10:00Z',
    user: 'Tien Tran',
  },
];

export const mockQuickActions: QuickAction[] = [
  {
    id: '1',
    label: 'Transfer Stock',
    icon: '🚚',
    href: '/transfers/new',
    color: 'red',
  },
  {
    id: '2',
    label: 'Add Product',
    icon: '📦',
    href: '/products/new',
    color: 'blue',
  },
  {
    id: '3',
    label: 'Send SMS',
    icon: '📱',
    href: '/sms/send',
    color: 'green',
  },
  {
    id: '4',
    label: 'View Reports',
    icon: '📊',
    href: '/reports',
    color: 'yellow',
  },
  {
    id: '5',
    label: 'Manage Distributors',
    icon: '👥',
    href: '/distributors',
    color: 'gray',
  },
];
